### ISSUE TITLE
Voby memory usage

### ISSUE THREAD

**Issue by krausest** [krausest/js-framework-benchmark#1045]
Voby's memory usage has increased a lot. We have to investigate whether it's a bug in the benchmark driver.

Here's a screenshot showing mem usage for recent voby versions:
![Screenshot from 2022-05-27 17-04-28](https://user-images.githubusercontent.com/3374055/170737233-36174e39-5266-458d-bf36-e56bfc0f843d.png)
Sadly I can't find out what benchmark driver (puppeteer or plawright) was used.
 
~~Comparing chrome 102 (https://krausest.github.io/js-framework-benchmark/current.html) and 101 (https://krausest.github.io/js-framework-benchmark/2022/table_chrome_101.0.4951.41.html) shows that memory usage has increased for all (?) frameworks somewhere between 400 and 700 kb. Voby appears to be the only framework that uses much more memory in two benchmarks (about 3,4 MBs). 
![Screenshot from 2022-05-27 18-19-32](https://user-images.githubusercontent.com/3374055/170739219-e73a4e52-aadd-4d2a-818a-378715ba0769.png)~~ This seems to be just the difference between playwright and puppeteer.

**Comment by krausest** [comment]
Memory usage differs between playwright (left) and puppeteer (right) benchmark driver:
![Screenshot from 2022-05-27 18-26-11](https://user-images.githubusercontent.com/3374055/170740213-90c7418b-cd82-4e20-a3ea-7980a397abdf.png)

**Comment by krausest** [comment]
Here are the results for chrome 102, benchmark 25 for puppeteer:
|Number of iterations|voby memory|solid memory|
|-|-|-|
|5|5.33|1.48|
|10|8.12|1.40|
|15|11.39|1.3|
|20|14.45|1.37|

So looks like a memory leak for voby either in the framework or due to the benchmark driver.

**Comment by krausest** [comment]
I merged you PR. Looks like the problem disappeared:
![Screenshot from 2022-05-27 19-59-15](https://user-images.githubusercontent.com/3374055/170765810-7544a0b0-c7b6-4ceb-9687-7d1f12d3cbc7.png)

I think we can close this issue again. @fabiospampinato Do you agree?

**Comment by krausest** [comment]
Here's the table for voby 0.23.2
|Number of iterations|voby memory|
|-|-|
|5|1.6|
|10|1.7|
|15|1.6|
|20|1.7|
Looks good to me.

**Comment by fabiospampinato** [comment]
> I merged you PR. Looks like the problem disappeared:

That's very interesting 🤔 I suppose then the most likely explanation is that when I looked at the numbers for v0.21.1 I didn't correctly inspect the heap, but there was an issue there, and then when looking at the heap for v0.23 I couldn't see a problem because there wasn't one. 

I'm still not sure what code caused the issue, but I'm glad it's resolved, yeah I think we can close this. 

Thanks for the help 👍
